blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('blogapp.urls', namespace = "blogapp")),
]

blogapp/urls.py
"""URL"""
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from blogapp import views
from blogapp.sitemaps import PostSitemap
from .feeds import LatestPostsFeed
app_name = "blogapp"

sitemaps = {
    "posts":PostSitemap,
}
urlpatterns = [
    path("", views.post_list, name = "post_list"),
    # path("", views.PostListView.as_view(), name = "post_list"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", views.post_detail, name ="post_detail"),
    path("<int:post_id>/share", views.post_share, name= "post_share"),
    path("tag/<slug:tag_slug>/",views.post_list,name = "post_list_by_tag"),
    path("sitemap.xml", sitemap, {"sitemaps":sitemaps},
    name='django.contrib.sitemaps.views.sitemap'),
    path("feed/",LatestPostsFeed(), name = "post_feed"),
    path("search/" ,views.post_search, name = "post_search")
]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

#Creating custom models
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")



class Post(models.Model):
    STATUS_CHOICES = (("draft", "Draft"), ("published","Published"),)
    title = models.CharField(max_length= 250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices= STATUS_CHOICES, default="draft")
    tags = TaggableManager()

    class Meta:
        ordering = ("-publish", )

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse("blogapp:post_detail", args=[self.publish.year, self.publish.month,
         self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name= "comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blogapp/forms.py
"""Importing Comment"""
from xml.etree.ElementTree import Comment
from django import forms
from .models import Comment
class EmailPostForm(forms.Form):
    """Emial post form class"""
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False,  widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    """Letting users fill the form"""
    class Meta:
        """Creating a comment"""
        model = Comment
        fields = ("name","email","body")

class SearchForm(forms.Form):
    """Creating the search form class"""
    query = forms.CharField()

blogapp/views.py
"""Model to create QuerySets"""
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from django.contrib.postgres.search import TrigramSimilarity
from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm



# Create your views here.
class PostListView(ListView):
    """ListView Class (Class Based Views)"""
    queryset = Post.published.all()

    context_object_name = "posts"
    paginate_by = 3
    template_name = "blogapp/post/list.html"

def post_list(request,tag_slug = None):
    """ListView Function"""
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        object_list = object_list.filter(tags__in = [tag])
    paginator = Paginator(object_list,2)
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, "blogapp/post/list.html", {"page":page, "posts":posts, "tag":tag})

def post_detail(request, year, month, day, post):
    """Details View (Function based views)"""
    post = get_object_or_404(Post, slug=post, status = "published", publish__year=year,
    publish__month = month, publish__day=day)
    comments = post.comments.filter(active = True)
    new_comment = None
    comment_form = CommentForm(data = request.POST)
    if request.method == "POST":
        comment_form = CommentForm(data = request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        else:
            comment_form = CommentForm()
    post_tag_ids = post.tags.values_list("id", flat = True)
    similar_posts = Post.published.filter(tags__in=post_tag_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags = Count("tags")).order_by("-same_tags",
     "-publish")[:4]
    return render(request, "blogapp/post/detail.html",{"post":post, "comments":comments,
     "new_comment": new_comment,"comment_form":comment_form, "similar_posts":similar_posts})

# Sharing a post
def post_share(request, post_id):
    """Created to share"""
    post = get_object_or_404(Post, id = post_id, status = "published")
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            clean_d = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{clean_d['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {clean_d['name']}\
                 comments: {clean_d['comment']}"
            send_mail(subject, message, "gyateng94@gmail.com", [clean_d["to"]])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, "blogapp/post/share.html",{"post":post, "form":form, "sent":sent})


def post_search(request):
    """Creating the get post search function"""
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                similarity = TrigramSimilarity("title",query),
                ).filter(similarity__gt=0.3).order_by("-similarity")
    return render(request, "blogapp/post/search.html",{
        "form":form,"query":query, "results":results
    })

blogapp/templates/blogapp/base.html
{% load static %} {% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link href='{% static "css/blogapp.css" %}' rel="stylesheet" />
  </head>
  <body>
    <div id="content">{% block content %} {% endblock %}</div>
    <div id="sidebar">
      <h2>My blog</h2>
      <p>This is my blog. I've written {% total_post %} post so far.</p>
      <h3>Latest posts</h3>
      {% show_latest_posts 3 %}
            <p>
      <a href = "{% url 'blogapp:post_feed' %}">Subscribe to my RSS Feed</a>
      </p>
      <h3>Most commented posts</h3>
      {% get_most_commented_post as get_most_commented_post %}
      <ul>
        {% for post in get_most_commented_post %}
        <li><a href = {{post.get_absolute_url}}>{{post.title}}</li>
        {% endfor %}
      </ul>

    </div>
  </body>
</html>

blogapp/templates/blogapp/post/detail.html
{% extends 'blogapp/base.html' %} {% load blog_tags %} {% block title%}
{{post.title}} {% endblock %} {% block content %}
<h1>{{post.title}}</h1>

<p class="date">Published {{ post.publish }} by {{post.author}}</p>
{{post.body|markdown}}
<p>
  <a href="{% url 'blogapp:post_share' post.id%}"> Share this post</a>
</p>
{% with comments.count as total_comments %}
<h2>{{total_comments}} comment{{total_comments|pluralize}}</h2>
{% endwith %}
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
  <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
</p>
There are no similar posts yet. {% endfor %} {% for comment in comments %}
<div class="comment">
  <p class="info">
    Comment {{ forloop.counter }} by {{ comment.name}} {{comment.created}}
  </p>
  {{ comment.body|linebreaks}}
</div>
{% empty %}
<p>There are no comment yet.</p>
{% endfor %} {% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add new Comment</h2>
<form method="post">
  {{comment_form.as_p}} {% csrf_token %}
  <p><input type="submit" value="Add Comment" /></p>
</form>

{% endif %} {% endblock %}

blogapp/templates/blogapp/post/latest_posts.html
<ul>
  {% for latest_post in latest_posts %}
  <li>
    <a href="{{latest_post.get_absolute_url}}"> {{latest_post.title}}</a>
  </li>

  {% endfor %}
</ul>

blogapp/templates/blogapp/post/list.html
{% extends "blogapp/base.html" %} 
{% load blog_tags %}
{% block title %}My Blog{% endblock %} 

{%block content %}
<h1>My Blog</h1>
{% if tag %}
<h2>
    Posts tagged with "{{tag.name}}"
</h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href = "{{ post.get_absolute_url }}">{{post.title}}</a>

</h2
<p class = "date">
    Published {{post.publish}} by {{post.author }}
</p>
{{ post.body|markdown|truncatewords_html:30 }}
<p class = "tags">Tags: {% for tag in post.tags.all %}
    
    <a href = "{% url 'blogapp:post_list_by_tag' tag.slug %}">
        {{tag.name}}
    </a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}</p>
{% endfor %}

{% include "pagination.html" with page=posts %}
{% endblock %}

blogapp/templates/blogapp/post/search.html
{% extends 'blogapp/base.html' %} {% load blog_tags %}Search {% block title %}
{% endblock %} {% block content %} {% if query %}
<h1>Post containing "{{query}}"</h1>
<h3>
  {% with results.count as total_results %} Found {{total_results}}
  result{{total_results|pluralize}} {% endwith %}
</h3>

{% for post in results %}
<h4><a href="{% url 'blogapp:post_search' %}">{{post.title}}</a></h4>
{{post.body|markdown|truncatewords_html:5}} {%empty%}
<p>There are not results for your query.</p>
{% endfor %}
<p><a href="{% url 'blogapp:post_search' %}">Search Again</a></p>
{% else %}
<h1>Search got posts</h1>
<form method="get">
  {{form.as_p}} {% csrf_token %}
  <input type="submit" value="Search" />
</form>
{% endif %} {% endblock %}

blogapp/templates/blogapp/post/share.html
{% extends "blogapp/base.html" %} {% block title %}Share a Post {% endblock %}
{% block content %} {% if sent %}
<h1>Email successfully sent</h1>
<p>"{{post.title}}" was successfully sent to {{form.cleaned_data.to}}.</p>
{% else %}
<h1>Share "{{post.title}}" by E-mail</h1>
<form method="POST">
  {{form.as_p}} {% csrf_token %}
  <input type="submit" value="Send e-mail" />
</form>
{% endif %} {% endblock %}

blogapp/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number}} of {{page.paginator.num_pages}}blog.
    </span>
    {% if page.has_next %}
    <a href="?page={{page.next_page_number}}">Next</a>
    {% endif %}
  </span>
</div>